defaults:
    - omics: fusion
    - metadata: caris_cmdb
    - training: fusion
    - override /omics/modalities/dna/architecture: mlm_4_layer_caris
    - override /omics/modalities/dna/data: caris_cmdb

anndata: ./datasets/caris/rna_cmdb.h5ad
sample_metadata_path: ./datasets/sample_metadata.pkl
data_file_prefix: fusion_caris_cmdb_

sample_index:
    join: intersection
    id_column: { dna: SampleID, rna: index }
