max_length: 768
component_configs:
  gene:
    encoder_type: LayerNormEncoder
    encode: false
    predict: true
    params:
      num_embeddings: true
      embedding_dim: 512
      padding_idx: 0
    combination: sum
    loss_param: 1.0
  geneinfo:
    encoder_type: PrecomputedEmbeddingsEncoder
    encode: true
    predict: gene
    params:
      weight_path: ./datasets/GenePTmodel3.genept_geneinfo.weight.pt
      vocab_path:  ./datasets/GenePTmodel3.genept_geneinfo.vocab.json
      trainable: false
      dtype: bf16
    combination: concat
  expression:
    encoder_type: FourierFractionEncoder
    encode: true
    predict: expression_bin
    params:
      embedding_dim: 512
      fourier_dim: 32
      f_min: 1.0
      f_max: 64.0
      add_logit: true
    combination: sum
  expression_bin:
    encoder_type: LayerNormEncoder
    encode: false
    predict: true
    params:
      num_embeddings: true
      embedding_dim: 128
      padding_idx: 0
    combination: concat
    loss_param: 1.0
