seed: 42
optimizer: AdamW
learning_rate: 5e-5
weight_decay: 1e-4
scheduler_curve: cosine
num_epochs: 40
train_test_split: 0.8
train_test_by_sample_metadata: false
scheduler_warmup_fraction: 0.1
batch_size: 512

pre_train_model: true
fine_tune_model: false
fine_tune_model_learning_rate: 0.000001

# DINO
dino_prototypes: 1024
dino_hidden: 2048
dino_bottleneck: 512
dino_head_lr_mult: 2.0
dino_head_decay: 5e-4
dino_student_temp: 0.13        # was 0.1
dino_teacher_temp_base: 0.10   # was 0.04 (start warm)
dino_teacher_temp_final: 0.06  # was 0.08 (end slightly cooler)
dino_teacher_m_base: 0.998     # was 0.996
dino_teacher_m_final: 0.9997   # was 0.9995
dino_center_momentum: 0.99

# DINO token crops per modality
dna_contrast_mask_rate: 0.25 # was 0.2 (decrease student maxprob)
rna_contrast_mask_rate: 0.33
moddrop_student_p: 0.0
moddrop_teacher_p: 0.0

# Masking (names are modality‑prefixed)
context_moddrop_p: 0.0

dna_shuffle_prob: 0.25
dna_masking_rate_start: 0.2
dna_masking_rate_steady: 0.2
dna_masking_rate_decay_epochs: 40
dna_set_loss_param: 1.0
dna_row_loss_param: 0.0 # 0.25
dna_ind_loss_param: 0.0 # 0.05  
dna_contrast_aug_warm_epochs: 3
dna_contrast_vaf_noise_hi: 0.004
dna_contrast_vaf_noise_lo: 0.003
dna_contrast_vaf_a_lo: 0.97
dna_contrast_vaf_a_hi: 1.03
dna_contrast_vaf_b_abs: 0.01
dna_contrast_vaf_q_step: 0.0

rna_shuffle_prob: 0.0
rna_masking_rate_start: 0.20
rna_masking_rate_steady: 0.20
rna_masking_rate_decay_epochs: 20
rna_set_loss_param: 1.0
rna_row_loss_param: 0.0
rna_ind_loss_param: 0.0


# Loss weights
w_dino: 0.75
dna_recon_meta_weight: 0.1
dna_contrast_meta_weight: 0.1
rna_recon_meta_weight: 0.1
rna_contrast_meta_weight: 0.1

byol:
  enabled: false
  weight: 0.2
  predictor_hidden: 1024
  use_batchnorm: true

visualization:
  save_self_attn: false